dodajem cetvrti
gkukolj-endava/goran-java-zadaci pull request #3
Opened 2018-10-03 14:59 UTC by gkukolj-endava

2018-10-03 20:52 UTC, BoskoNikolic requested changes
Mozda nije najbolje srocen tekst zadatka :) Trebalo je da se unese duzina niza, svi elementi i broj koji se trazi. Ispravi, pa ponovo posalji na review.

Inace jako je lepo sto komentarises kod.

2018-10-03 20:52 UTC, BoskoNikolic commented on src/zadatak4/SortiranjeNiza.java
> +	public static int unosBroja() {
Zasto public?

2018-10-05 07:02 UTC, BoskoNikolic requested changes
Ispravi kod po kementarima, i pokusaj da sve sto moze, izdvojis u zasebne metode.

2018-10-05 07:02 UTC, BoskoNikolic commented on src/zadatak4/SortiranjeNiza.java
> +		int unosKorisnika = unos.nextInt();
Nepotrebno uvodjenje nove promenljive, odmah vrati vrednost unos.nextInt()

2018-10-05 07:02 UTC, BoskoNikolic commented on src/zadatak4/SortiranjeNiza.java
> +			System.out.println("Unesite broj niza: ");
Ispravi poruku "Unesite prvi, drugi, n-ti clan niza. Malo je nejasno ovako.

2018-10-05 07:02 UTC, BoskoNikolic commented on src/zadatak4/SortiranjeNiza.java
> +		for (int brojac : niz) {
Gleadj da uvek pravis posebne metode, kad god je to moguce, da sto manje koda guras u main.

2018-10-05 07:02 UTC, BoskoNikolic commented on src/zadatak4/SortiranjeNiza.java
> +		if (velicinaNiza > 4) {
Isto dobar kandidat za zasebnu metodu.

2018-10-05 07:02 UTC, BoskoNikolic commented on src/zadatak4/SortiranjeNiza.java
> + *         ZADATAK4: Za uneti niz celih brojeva duzine n (koja se takodje
Mislim da sam i Vladimiru skrenuo paznju, svakao je nasa greska, duzina niza ne sme da bude manja od 5 (posto ispisujes prvih 5 clanova), ispravi ako ti nije tesko(mada radi i ovo sto si napisao)

2018-10-06 11:01 UTC, BoskoNikolic requested changes
Program radi, ali par nekih sitnih izmena je potrebno, cisto da bude lepsi kod i da je korisniku jasnije za upotrebu.

2018-10-06 11:01 UTC, BoskoNikolic commented on src/zadatak4/SortiranjeNiza.java
> +				continue;
posto "continue" ovde nema nikakvu svrhu, obrisi ga i promeni uslov tako imas samo if bez else-a i continue-a.

2018-10-06 11:01 UTC, BoskoNikolic commented on src/zadatak4/SortiranjeNiza.java
> +			System.out.println("Unesite " + (brojac + 1) + " broj niza: ");
samo dodaj tacku posle rednog broja u komentaru

2018-10-06 11:01 UTC, BoskoNikolic commented on src/zadatak4/SortiranjeNiza.java
> +			System.out.print(niz[brojac] + " ");
dodaj kometar "Prvih 5 clanova niza su: ... " da bi korisnik znao sta mu je tih 5 cifara koje se pojave na kraju.

2018-10-08 19:08 UTC, BoskoNikolic approved these changes
Sve je popravljeno, mozes da komitujes.

2018-10-09 06:35 UTC, endavamarko approved these changes

2018-10-09 07:48 UTC, merged