zadatak 5
gkukolj-endava/goran-java-zadaci pull request #4
Opened 2018-10-04 17:00 UTC by gkukolj-endava

2018-10-05 10:26 UTC, endavamarko commented on src/zadatak5/Elipsa.java
> +	// preklopljena metoda super klase za proracun povrsine
Ako se vec pisu komentari metoda onda je najbolje da budu u obliku JavaDoc, a ovi obicni komentari idu u telo metode. JavaDoc format je:
/**
 *opis metoda
 *@param  navedeni parametri ako ih ima
 *@return     naveden povratni tip ako nije void
 */

2018-10-06 12:48 UTC, BoskoNikolic requested changes
Pored dole navedenih kometara i tebi, kao i Vladimiru, zamerka na ienovanje get/set metoda i promenljivih.

poluprecnikKruga je mnogo jasnije od poluprecnik.

2018-10-06 12:48 UTC, BoskoNikolic commented on src/zadatak5/NejednakostranicniTrougao.java
> +		if (!((stranicaA + stranicaB) > stranicaC && (stranicaA + stranicaC) > stranicaB && stranicaC > stranicaA)) {
Sjajno je sto si se setio ovoga, samo gledaj da obezbedis da se ne racunaju obim i povrsina u ovom slucaju i da toString salje odgovarajucu poruku u tom slucaju.  Mozda ovoj proveri nije mesto u konstruktoru ?

2018-10-06 12:48 UTC, BoskoNikolic commented on src/zadatak5/Pravougaonik.java
> +		return 2 * visina + 2 * sirina;
Distributivnost ;)

2018-10-06 12:48 UTC, BoskoNikolic commented on src/zadatak5/NejednakostranicniTrougao.java
> +	public double izracunajPovrsinu() {
Kad vec imas stranice i poluobim, iskoristi heronov obrazac za proracun povrsine. Onda nema potrebe da racunas visinu.

2018-10-06 12:48 UTC, BoskoNikolic commented on src/zadatak5/NejednakostranicniTrougao.java
> +		double poluobim = (stranicaA + stranicaB + stranicaC) / 2;
Nemoj da dupliras kod. Izracunaj poluobim na osnovu obima ili obrnuto. Mozda u ovom slucaju to nije nista strasno(i nije) ali kad budes radio na ozbiljnom projektu treba izbegavati pisanje istog koda.

2018-10-06 12:48 UTC, BoskoNikolic commented on src/zadatak5/Krug.java
> +		return poluprecnik * poluprecnik * Math.PI;
kad vec svuda koristis pow() budi konzistentan.

2018-10-08 19:20 UTC, BoskoNikolic requested changes
samo sitna izmena kod ispitivanja uslova za konstrukciju trougla. sve ostalo radi kako treba.

2018-10-08 19:20 UTC, BoskoNikolic commented on src/zadatak5/NejednakostranicniTrougao.java
> +		if (!((stranicaA + stranicaB) > stranicaC && (stranicaA + stranicaC) > stranicaB && stranicaC > stranicaA)) {
if/else ti nisu potrebni, odmas vrati boolen vrednost ovog izraza.

2018-10-09 12:34 UTC, BoskoNikolic approved these changes

2018-10-09 12:34 UTC, merged