zadatak 6
gkukolj-endava/goran-java-zadaci pull request #5
Opened 2018-10-05 14:07 UTC by gkukolj-endava

2018-10-06 13:56 UTC, BoskoNikolic requested changes
Ti si delimicno implementirao zastitu  unosa od losih podataka, ali dopuni i za ostale podatke. 

Takodje obrisi sve funkcije koje se ne koriste. U ovom zadatku nije trazeno da se prave 3 konstruktora svake klase pa mozes i to obrisati.

2018-10-06 13:56 UTC, BoskoNikolic commented on src/zadatak6/Kuca.java
> +			throw new IllegalArgumentException("Pogresan unos povrsine okucnice, unesite broj veci od nule");
Tri puta ponavljas isti kometar. Napravi konstantu.

2018-10-06 13:56 UTC, BoskoNikolic commented on src/zadatak6/Vlasnik.java
> +		if (jmbg.contains("[a-zA-Z]+") == true || jmbg.length() != 13) {
== true je visak

2018-10-06 13:56 UTC, BoskoNikolic commented on src/zadatak6/Vlasnik.java
> +		if (jmbg.contains("[a-zA-Z]+") == true || jmbg.length() != 13) {
== true je visak

2018-10-06 13:56 UTC, BoskoNikolic commented on src/zadatak6/Stan.java
> +			throw new IllegalArgumentException("Pogresan unos povrsine podruma, unesite broj veci od nule");
isti string se vise puta ponavlja. Napravi konstantu

2018-10-06 13:56 UTC, BoskoNikolic commented on src/zadatak6/Nekretnina.java
> +			throw new IllegalArgumentException("Pogresan unos kvadrature, unesite broj veci od nule");
Napravi konstantu od poruke koja se ispisuje umesto sto dupliras kod.

2018-10-06 13:56 UTC, BoskoNikolic commented on src/zadatak6/Nekretnina.java
> +			throw new IllegalArgumentException("Pogresan unos zone, unesite ceo broj od 1-4");
Napravi konstantu od poruke koja se ispisuje umesto sto dupliras kod.

2018-10-06 13:56 UTC, BoskoNikolic commented on src/zadatak6/Main.java
> +			Vlasnik vlasnik1 = new Vlasnik("Jan", "Petar", "1234561234561", "123450");
U ime i prezime mogu da unesem brojeve i specijane karaktere(barem one koje ne bi trebalo da stoje u imenu).

2018-10-06 13:56 UTC, BoskoNikolic commented on src/zadatak6/Vlasnik.java
> +		if (jmbg.contains("[a-zA-Z]+") == true || jmbg.length() != 13) {
napravi konstantu od regexa

2018-10-06 13:56 UTC, BoskoNikolic commented on src/zadatak6/Main.java
> +			Vlasnik vlasnik2 = new Vlasnik("Mia", "Minic", "1200044234561", "166890");
mogu da unesem broj licne karte od 40 brojeva, slova i specijanih znakova.

2018-10-08 15:37 UTC, endavamarko commented on src/zadatak6/Stan.java
> +		return (getKvadratura() + (getPovrsinaPodruma() + getPovrsinaTerase() * 33 / 100)) * izracunajCenuKvadrata();
Ovde formula nije dobra, treba da  ide getPovrsinaPodruma()+getPovrsinaTerase() pa sve to puta 0.33, a trenutno je samo getPovrsinaTerase() puta 0.33 tj. fali zagrada pre mnozenja sa 0.33.

2018-10-08 19:51 UTC, BoskoNikolic requested changes
Pogledaj komentare i implementiraj ih.

2018-10-08 19:51 UTC, BoskoNikolic commented on src/zadatak6/Vlasnik.java
> +		if (prezime.matches(REG_EXP_2)) {
Prezime moze da ima i apostrof, izmeni regex.

2018-10-08 19:51 UTC, BoskoNikolic commented on src/zadatak6/Main.java
> +public class Main {
Stampaj one podatke koji su ispravni.

2018-10-08 20:02 UTC, BoskoNikolic requested changes
Pogledaj komentare, i pokusaj da ih implementiras.

2018-10-09 13:56 UTC, BoskoNikolic requested changes
Regex za prezime i dalje nije ispravan. Apostrof moze biti deo prezimena.

2018-10-09 15:40 UTC, BoskoNikolic approved these changes

2018-10-09 15:40 UTC, merged