zadatak 7
gkukolj-endava/goran-java-zadaci pull request #6
Opened 2018-10-09 11:20 UTC by gkukolj-endava

2018-10-09 14:37 UTC, BoskoNikolic requested changes
Obrati paznju na komentare i izbaci sve get/set mtode koje se ne koriste kao i bespotrebne konstruktore.

2018-10-09 14:37 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +	private static final String REG_EXP_1 = "^[\\-'\\s]?[a-zA-Z]+";
Apostrof moze da bude deo prezimena. Izmeni regex za unos prezimena.

2018-10-09 14:37 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +	private static final String LOS_UNOS_IMENA = "Rec mora da sadrzi samo slova";
Izmeni kometar. Valjda "Ime mora da sadrzi...

2018-10-09 14:37 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +			upis.close();
Bespotreban close posto vec koristis try-with-resources

2018-10-09 14:37 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +		} while (!(a >= 0 && a <= 100));
Stampaj poruku kada uneti broj poena nije izmedju 0 i 100. Mlao je nejasno ovako kada se no stop ponavalja "Unesite broj poena sa testa:"

2018-10-09 14:37 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +				System.out.println("Upis je sacuvan!");
Ispravi malo komentar. Upis se nalazi u kom file-u i na kojoj lokaciji.

2018-10-09 14:37 UTC, BoskoNikolic commented on src/zadatak7/Student.java
> +public class Student implements Comparable<Student> {
Probaj da preradis zadatak tako da ne implementria Comparable.

2018-10-09 14:37 UTC, BoskoNikolic commented on src/zadatak7/Student.java
> +	public String toString() {
Posto to tekstom zadatka nije trazeno nemoj da Override-ujes toString nego stampaj poruku na drugi nacin.

2018-10-09 14:37 UTC, BoskoNikolic commented on src/zadatak7/Student.java
> +	public int ocenaStudenta(int brojPoena) {
int brojPoena se nigde ne koristi

2018-10-09 14:37 UTC, BoskoNikolic commented on src/zadatak7/Student.java
> +	@Override
Moraces i ovo da izmenis kad izbacis Implementaciju Comparable-a.

2018-10-09 14:39 UTC, BoskoNikolic requested changes

2018-10-09 14:39 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +		ArrayList<Student> studenti = new ArrayList<>();
Koristi List umesto ArrayList

2018-10-09 14:39 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +			System.out.println("Unesite ime studenta: ");
Hajde da malo zakomplikujemo zadatak, Ime i prezime moraju da pocnu velikim slovima :)

2018-10-09 17:05 UTC, endavamarko commented on src/zadatak7/Student.java
> +		super();
super() nije neophodno ovde jer ova klasa samo implementira interfejs

2018-10-09 17:10 UTC, endavamarko requested changes

2018-10-09 17:10 UTC, endavamarko commented on src/zadatak7/Student.java
> +		super();
ovde moze isto bez super()

2018-10-10 09:45 UTC, BoskoNikolic requested changes
Zadatak ne radi.

2018-10-10 09:45 UTC, BoskoNikolic commented on src/zadatak7/Student.java
> +	public String toString() {
NIje Ispravljeno.

2018-10-10 09:45 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +						"Upis je sacuvan u fajlu \"ocene.txt\", koji se nalazi na lokaciji C:\\Users\\goran.kukolj\\eclipse-workspace\\JavaZadaci\\ocene.txt!");
Hoce li na na mom racunaru lokacija biti C:\\Users\\goran.kukolj ? Daj relativnu putanju do file-a. Npr. najbolje je da ga stampas u istom folderu gde je i zadatak.

2018-10-10 09:45 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +	private static final String REG_EXP_1 = "^[A-Z][\\-'\\s]?[a-z]+";
Mogu da unesem ime Blabla ()

2018-10-10 09:45 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +	private static final String REG_EXP_2 = "^([A-Z'][a-z]*)+$";
Mogu da unesem prezime Blabla () .

Takodje ako unesem prezime sa apostrofom O' Tool npr. dobijam ovo kao ispis
Unesite broj poena od 0 do 100: 
Pogresno ste uneli broj poena, 
Unesite broj poena od 0 do 100: 
Pogresno ste uneli broj poena, 
Unesite broj poena od 0 do 100: 

Uvek testiraj pre nego posaljes na review-u.

2018-10-10 09:50 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +	private static String unosImena() {
Unos imena i prezimena su potpuno iste metode, samo se razlikuju regex i komentar. Izbegavaj ponavljanje koda, napravi jednu metodu kojoj ces da prosledjujes potrebne parametre.

2018-10-10 15:58 UTC, BoskoNikolic requested changes
Glavni problem je sto se file ne stampa, ostalo su sitne ispravke.

2018-10-10 15:58 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +	private static final String REG_EXP_2 = "^[A-Z]['\\sA-Z]*?[a-z]+$";// "^([a-zA-Z ']*)+$";
obrisi zakomntarisani kod

2018-10-10 15:58 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +		File file = new File("C:\\Users\\goran.kukolj\\eclipse-workspace\\JavaZadaci\\src\\zadatak7\\ocene.txt");
C:\\Users\\goran.kukolj\\eclipse-workspace\\JavaZadaci\\src\\   kod mene na masini ovo ne moze da se stampa

2018-10-10 15:58 UTC, BoskoNikolic commented on src/zadatak7/Student.java
> +	protected Student(String ime, String prezime, int brojPoena) {
ovo se, cini mi se, nigde ne koristi

2018-10-11 14:29 UTC, BoskoNikolic requested changes

2018-10-11 14:29 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +					// TODO Auto-generated catch block
??? sta ce ti TODO

2018-10-11 14:29 UTC, BoskoNikolic commented on src/zadatak7/Main.java
> +					e.printStackTrace();
ovo stampaj

2018-10-11 14:29 UTC, BoskoNikolic commented on src/zadatak7/Student.java
> +	 * @param brojPoena
nemas vise parametar

2018-10-11 17:57 UTC, BoskoNikolic approved these changes

2018-10-12 07:55 UTC, endavamarko approved these changes

2018-10-12 07:55 UTC, merged